### Create a new person

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test posting from VS REST Client",
    "number": 123
}

### Delete the information of a person

DELETE http://localhost:3001/api/persons/4

### Get all listed persons

GET http://localhost:3001/api/persons

